/**
 * api/signal.js  —  Vercel Serverless Function
 *
 * Minimal room-coordination relay for Stickman Fighter online mode.
 * Actual WebRTC signaling (offer/answer/ICE) is handled by PeerJS's
 * public cloud. This endpoint handles:
 *
 *   GET  /api/signal?action=create          → generate a fresh room token
 *   POST /api/signal?action=register        → host advertises { token }
 *   GET  /api/signal?action=check&room=TOK  → check if room is live
 *
 * State is in-memory (best-effort) — suitable for ephemeral game rooms.
 * If a Vercel instance cold-starts, existing rooms are gone; clients fall
 * back to attempting a direct PeerJS connection anyway.
 */

/* ---------- in-memory store ---------- */
const _rooms = new Map();
const ROOM_TTL_MS = 10 * 60 * 1000; // 10 minutes

function cleanup() {
    const now = Date.now();
    for (const [k, v] of _rooms) {
        if (now - v.ts > ROOM_TTL_MS) _rooms.delete(k);
    }
}

const SAFE_TOKEN_RE = /^[a-z0-9]{10,12}$/; // matches tokens generated by network.js

/* ---------- handler ---------- */
export default function handler(req, res) {
    // CORS — allow any origin (static frontend may be served from a CDN)
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    if (req.method === 'OPTIONS') return res.status(200).end();

    cleanup();

    const { action, room } = req.query;

    /* ── GET /api/signal?action=create ───────────────── */
    if (req.method === 'GET' && action === 'create') {
        const token = _genToken();
        return res.status(200).json({ token });
    }

    /* ── POST /api/signal?action=register ────────────── */
    if (req.method === 'POST' && action === 'register') {
        let body = req.body;
        if (typeof body === 'string') {
            try { body = JSON.parse(body); } catch (_) { body = {}; }
        }
        const token = body && body.token;
        if (!token || typeof token !== 'string' || !SAFE_TOKEN_RE.test(token)) {
            return res.status(400).json({ error: 'Invalid token' });
        }
        // Update or create room entry
        _rooms.set(token, {
            ts: Date.now(),
            players: ((_rooms.get(token) || {}).players || 0) + 0, // keep count reset-safe
        });
        return res.status(200).json({ ok: true, token });
    }

    /* ── GET /api/signal?action=check&room=TOKEN ─────── */
    if (req.method === 'GET' && action === 'check') {
        if (!room) return res.status(400).json({ error: 'Missing room' });
        const entry = _rooms.get(room);
        return res.status(200).json({ exists: !!entry, token: room });
    }

    /* ── Health-check ────────────────────────────────── */
    return res.status(200).json({ status: 'ok', ts: Date.now() });
}

/* ---------- helpers ---------- */
function _genToken() {
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
    // "sf" prefix keeps the peer ID namespace distinct on the PeerJS public server
    let t = 'sf';
    for (let i = 0; i < 8; i++) t += chars[Math.floor(Math.random() * chars.length)];
    return t;
}
